### ISSUE TITLE
Issue when starting with pm2?

### ISSUE THREAD

**Issue by developedbyalex** [iValencitoh/Steam-Hour-Booster-2FA-Support#31]
Using command:
`pm2 start accountHandler.js --name SteamBooster`

Error:

1|SteamBooster  | * Detected 2 account(s) in the config.
1|SteamBooster  | * Starting idling 2 account(s).
1|SteamBooster  | * Press CTRL + C to exit.
1|SteamBooster  | * Timer: 00:00:01
1|SteamBooster  | TypeError: process.stdout.cursorTo is not a function
1|SteamBooster  |     at EventEmitter.<anonymous> (/home/alex2/vaporBooster-main/src/hourBooster.js:165:19)
1|SteamBooster  |     at /home/alex2/vaporBooster-main/node_modules/easytimer.js/dist/easytimer.js:171:25
1|SteamBooster  |     at Array.forEach (<anonymous>)
1|SteamBooster  |     at EventEmitter.emit (/home/alex2/vaporBooster-main/node_modules/easytimer.js/dist/easytimer.js:170:26)
1|SteamBooster  |     at dispatchEvent (/home/alex2/vaporBooster-main/node_modules/easytimer.js/dist/easytimer.js:597:20)
1|SteamBooster  |     at dispatchEvents (/home/alex2/vaporBooster-main/node_modules/easytimer.js/dist/easytimer.js:360:9)
1|SteamBooster  |     at Timeout.updateTimerAndDispatchEvents [as _onTimeout] (/home/alex2/vaporBooster-main/node_modules/easytimer.js/dist/easytimer.js:329:7)
1|SteamBooster  |     at listOnTimeout (node:internal/timers:559:17)
1|SteamBooster  |     at processTimers (node:internal/timers:502:7)
PM2             | App [SteamBooster:1] exited with code [1] via signal [SIGINT]
PM2             | App [SteamBooster:1] starting in -fork mode-
PM2             | App [SteamBooster:1] online

**Comment by f1xc0d3** [comment]
same

**Comment by f1xc0d3** [comment]
try disable clock for pm2 or use screen

**Comment by developedbyalex** [comment]
> 

Did it work for you

**Comment by valnssh** [comment]
Thanks for the report.

The project has since been completely rewritten, and the current implementation no longer relies on terminal cursor manipulation.

Closing as fixed by rewrite / no longer applicable.
